{
 "title": "Application Metrics & Logs Dashboard",
 "tags": [
  "terraformed",
  "app",
  "flask"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Throughput by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count[5m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Latency (p95) by Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(flask_http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "p95 {{endpoint}}"
    }
   ]
  },
  {
   "title": "4xx / 5xx Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status=~\"4.*|5.*\"}[5m])) by (status, endpoint)",
     "legendFormat": "{{status}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Process Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "App Memory ({{instance}})" }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{service_name=\"keystone-app\"}"
    }
   ]
  }
 ]
}