apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      containers:
      - name: sample-api
        image: sample-api:latest # This will be overwritten by Kustomize
        ports:
        - containerPort: 8080
