apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: sample-api
    newName: 123456789.dkr.ecr.eu-west-1.amazonaws.com/sample-api # Use AWS ECR in Production
    newTag: v1.0.0

patches:
  - path: deployment-patch.yaml
