apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Tell Kustomize what we are overriding
resources:
  - ../../base

# Override the image name (e.g., to use a local image in minikube)
images:
  - name: sample-api
    newName: sample-api
    newTag: local-dev

# Apply environment specific patches
patches:
  - path: deployment-patch.yaml
